### ISSUE TITLE
Gluster-S3 compliance  with ACL support

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [gluster/integration#11]
Gluster-s3 with ACL support.

**Comment by nixpanic** [comment]
@vredara sent [an email](http://lists.openstack.org/pipermail/openstack-dev/2017-June/118027.html) to check what the plans of the [Swift3](https://github.com/openstack/swift3).

**Comment by vredara** [comment]
ACL support is there in swift3 , we have to make s3_acl = true in proxy-server.conf . However we have to change config files for gluster-container. will send new PR for that.
